name: PigmanSurvie
version: '${project.version}'
main: fr.skytryx.pigmansurvie.PigmanSurvie
api-version: 1.20
commands:
  stafftp:
    description: Command to stafftp (teleport whilst going into spectator mode)
    permission: survie.staff.stafftp
    usage: "ยง3Usage: /stafftp <player>"
  invsee:
    description: Command to see the inventory of a specific player
    permission: survie.staff.invsee
    usage: "ยง3Usage: /invsee <player>"
  mine:
    description: teleports you to the mine world
    usage: "ยง3Usage: /mine"
  xpbottle:
    description: Command to give you xp bottles you can consume
    usage: "ยง3Usage: /xpbottle"